### ISSUE TITLE
Inventory quantity error

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#432] opened 2018-09-05 14:48 UTC
Hello,
Look at 1 example as an attachment (item #2342). The last inventory adjustment mentions that we went from 1 to 5. Why do we only have 3 of them in the inventory quantity then? Physically we have 5 and not 3. We rely on repairdesk for our inventory, but the quantities do not work. It is not suposed happened!
<img width="933" alt="item 2342" src="https://user-images.githubusercontent.com/40500094/45101276-1de9b180-b0f9-11e8-8bc2-11b463f84f7d.png">

_French:
Bonjour,
Regardez 1 exemple en pièce jointe (item #2342). Le dernier ajustement d'inventaire mentionne que nous sommes passé de 1 à 5. Pourquoi en avons nous seulement 3 d'inscrit dans la quantité en inventaire alors? Physiquement nous en avons 5 et pas 3. Nous nous fions à repairdesk pour notre inventaire, mais les quantités ne fonctionnent pas. Ce n'est pas suposé arrivé!_

**Comment by usmanalikhan93** [comment] 2018-09-13 05:49
Hi @JessicaSOS  

I hope you are doing well. We are reviewing your issue internally but unable to reproduce this issue. If I get something on this, I will let you know ASAP. 

Thanks 
Usman Ali.

**Comment by quangc** [comment] 2018-10-03 12:04
What is the latest? How come it cannot be reproduced? It should have system log of why the number change from 5 to 3. Either human or system make these changes, it must records in the system.

**Comment by JessicaSOS** [comment] 2018-10-03 13:39
It's random, it's not every time. If I know what is causing it, I will mention it to you, but it is not the case.

**Comment by usmanalikhan93** [comment] 2018-12-13 06:38
Thanks @JessicaSOS

**Comment by usmanalikhan93** [comment] 2019-01-01 06:40
Hi @JessicaSOS 

I have come up with one use case after testing, this issue comes is case of e.g. when you are logged in on store A and in inventory transfer you select from store B and to store C, it does not log history against that inventory. So for now I recommend you that please select from store in which you are logged in. 

Furthermore, I am discussing this with developer for log transfer history in this case. I will update you when I get more info on this. 

Usman Ali

**Comment by usmanalikhan93** [comment] 2019-01-08 14:36
Hi @JessicaSOS 

I hope you are doing well. We have released a fix for this issue as I have mentioned the use case earlier. Now history will be come up in inventory in these cases. I hope in future, you will not face these issues again related to missing transactions. 

For now I am closing all tasks you reported related to missing inventory.

**Closed** 2019-01-08 14:37 UTC
Labels: Bug, Resolved

**Comment by JessicaSOS** [comment] 2019-01-23 16:08
Hello,
We are only connected to 1 store when this problem is displayed. I understand that I can only see the history of the store I am connected to. The history of the item is however not supposed to miss transactions. As in the example, go from 5 to 3 in the same store without knowing the reason. I really hope you have corrected this problem.

**Comment by JessicaSOS** [comment] 2019-01-23 16:12
I did not need to look far, the same item ... One or more transaction missing. See Attachment.
This task should be reopened please.
<img width="944" alt="same item" src="https://user-images.githubusercontent.com/40500094/51620175-d32dd200-1eff-11e9-8233-d14a38723a3c.png">

--
Je n'ai pas eu besoin de chercher bien loin, le même item... Il manque une ou plusieurs transaction. Voir pièce jointe. 
Cette tâche devrait être réouverte svp.
