### ISSUE TITLE
Glitchy Repairs Processing

### ISSUE THREAD

**Issue by Stylemyphones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1710] opened 2021-09-20 22:38 UTC
Hello,
Please see the attached video for more information.

This is a glitch that happens quite often when trying to select the 3 dots for in order to check details on a part before selecting it during a POS repair transaction.

It is very time consuming and sometimes prevents the processing of this type of transactions.

I hope it is a bug and that it can be fixed soon.

Thanks in advance and Best Regards!!

https://user-images.githubusercontent.com/83790373/134085723-6d52216d-25ca-471b-90ac-9602846befb2.mp4  [](url)

**Comment by Repairdesk-QA** [comment] 2021-09-21 05:38
Hey @Stylemyphones 
Azka here,
I hope you are doing well.
Thanks for reaching out to us. I have checked your descriptive concern and it is working fine for us. I believe you have uploaded a wrong video as I couldn't get any help from the video. 
Can you please reshare the video so I can have clarity of  bug you are facing.
I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks & Regards

**Comment by Stylemyphones** [comment] 2021-09-21 18:20
Here is a rerecorded video
https://watch.screencastify.com/v/DvF9aeCt1UOYIIs60v6J

**Comment by Repairdesk-QA** [comment] 2021-09-22 11:03
Hey @Stylemyphones 
I hope you are doing well. 
I have checked your concern on windows and Mac and it didn't reproduced. Kindly please contact any of our support ninja through live chat.
Thanks & Regards
Azka

**Comment by Stylemyphones** [comment] 2021-09-22 17:11
Hi Azka,
Thank you for your messages.

Did you by chance try this on a desktop computer or a laptop?
It seems to only be happening on a laptop :(

**Comment by Repairdesk-QA** [comment] 2021-09-23 04:48
Hi again,
Thanks for your response. 
We had checked your concern on laptop with different browsers but unable to reproduce. You do not need to worry. We have got you covered here.
One of our support guy Fahad Imran has left you an email for your better assistance. Kindly collaborate with him for better understanding of the issue.
Thanks & Regards

**Comment by Stylemyphones** [comment] 2021-09-23 18:30
Thank you, I'll look for the email.

Do you know if he emailed sarah2004_cc@yahoo.com or zams9@outlook.com?

**Comment by Repairdesk-QA** [comment] 2021-11-17 12:54
Hello @Stylemyphones,
Hope you are doing well.

I have gone through the above-mentioned issue and it seems that I will need more information regarding the issue.
I will request you to schedule a call with **_Fahad Imran, Manager Customer Success and Support_**. Kindly book a slot from the link in order to connect with him:
https://calendly.com/fahadimran

I am sure he will be able to assist with the above query and take relevant information so we can address your concerns timely.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Stylemyphones** [comment] 2021-11-17 18:17
Done! I have scheduled for tomorrow.

Thank You & Best Regards,
Alejandra Salazar
Stylemyphones

**Comment by Repairdesk-QA** [comment] 2021-11-18 04:18
That's great!
I hope this will solve your issue.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-12-10 05:28
Hello @Stylemyphones,
Hope you are doing well.

Since you have scheduled a call with **_Sir Fahad Imran_**,  I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain

**Comment by Stylemyphones** [comment] 2021-12-10 18:00
Hello,
Thank you for your message!

There was actually still no resolution to this glitch after my call with Sir Fahad Imran, he said he would keep looking into it.
However, I will definitely be in touch if anything else comes up, and please, you do the same if you know of any advances with this issue.

Best Regards,
Alejandra Salazar.

**Comment by Repairdesk-QA** [comment] 2021-12-13 05:02
Hello @Stylemyphones,
Hope you are doing well.

I've double-checked your concern and is working fine on my end. Kindly have this video for reference:
https://www.screencast.com/t/OQUKwLFIJQYb

There might be some issues with your device.
Can you please check at your end?
Also, I will keep you updated with the findings of Sir Fahad Imran.

Until then, just be with us. We really appreciate your time and effort to **_RepaiDesk_**.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-12-13 12:55
Hello again @Stylemyphones,
I have discussed your issues with Sir Fahad Imra, he is looking into this. Also, he has already reported your other issues and are in progress.
He will update you shortly about them.
Closing this task, for now, our support team will contact you shortly about the updates.

If you have any other issues, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Closed** 2021-12-13 12:55 UTC
Labels: customer updated, Parts In Repairs

**Comment by Stylemyphones** [comment] 2021-12-14 22:15
Thank you Quratul Ain.

I don't think that video quite shows the areas where the issue was happening, but I have checked with the employee having the issues, and he doesn't seem to be having problems any more, so for that I thank you and the team.

Best Regards,
Alejandra Salazar.

**Comment by Repairdesk-QA** [comment] 2021-12-15 11:39
Hey @Stylemyphones,
I hope you are doing well! 

Ayesha here. Glad to know that everything is working fine on your end. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
