### ISSUE TITLE
SMS confirmation for parts in stock

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#493] opened 2018-11-01 19:54 UTC
Hello,
I enabled the option to send a confirmation SMS to the customer after making an appointment. It's really great and it works well. What I wonder, the confirmation sms is sent to the customer that we have in stock the room to perform the repair of the customer's device or not. This can cause a problem if the part is no longer available in inventory.

When the bundle will be fixed and modifiable only by the admin (issue # 421), will it be possible to add an option so that the appointments take into account the parts in inventory in the selected store? The SMS confirmation could be different depending on whether the part is in stock or not. What do you think?

--
french:
Bonjour,
J'ai activé l'option d'envoyer un sms de confirmation au client suite à la prise de rendez-vous. C'est vraiment super et sa fonctionne bien. Ce que je me demande, les sms de confirmation s'envoie au client que nous ayons en inventaire la pièce pour effectuer la réparation de l'appareil du client ou pas. Ce qui peut causé problème si la pièce n'est plus disponible en inventaire.

Lorsque les bundle seront corrigé et modifiable uniquement par les admin (issue #421), est ce que se sera possible d'ajouter une option pour que les rendez-vous prennent considération des pièces en inventaire dans le magasin sélectionné? Le SMS de confirmation pourrais être différent tout dépendant si la pièce est en inventaire ou pas. Qu'en pensez-vous?

**Comment by Uzair-RepairDesk** [comment] 2018-11-06 05:39
Hi @JessicaSOS 
Thank you for sharing this with us. I want to notify you that Part bundle is not directly linked with "Appointment (Leads)" functionality. 
Its only assign the part to specific repair service when you convert lead into a ticket.
The reason is that appointment (lead) is not confirmed. When you convert into a ticket, lead is marked with status "Won" and then the part is assigned to a ticket according to the bundle. 
The best possible workaround I can suggest you is when you find the available part stock that can be linked with a ticket, you can go to Manage Leads > Action to specific Lead > Scroll down the page and "Send Email" to the customer. 
**Check screenshot attached.** 
You can put the description about the available part and send a specific email to the customer. 

Hope it helps. Thanks
![send email-manage lead](https://user-images.githubusercontent.com/22955861/48044931-12297280-e1b0-11e8-9d10-a787fab05f16.png)

**Comment by JessicaSOS** [comment] 2018-11-06 19:55
I understand what you mention to me. I also understand that leads do not remove any piece of inventory and that's perfect as well. What I'm wondering is if it's possible for the lead to consider inventory parts when the customer clicks "make an appointment". Without making any adjustments, simply by confirming that a piece is available before sending a confirmation, or having 2 different notifications. What do you think? Do you understand the nuance I'm trying to mention?

**Comment by Uzair-RepairDesk** [comment] 2018-11-09 06:02
Yes, I got that but I am wondering that we cannot link inventory item with Appointment/Leads as it's not confirmed for the final sale. 
The best workaround i can suggest this time is to check part availability according to repair service and send notification to customer about the part availability.

**Closed** 2018-11-09 06:03 UTC
Labels: Customer Updated - Waiting For further information

**Comment by JessicaSOS** [comment] 2018-11-13 15:14
But, without making an inventory adjustment for a pay / lead, is it possible to add an option for the appointments to take inventory parts into consideration in the selected store? The confirmation SMS could be different depending on whether the part is in stock or not.
