### ISSUE TITLE
Employee Productivity Report - Completed Repairs Show twice

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1614] opened 2021-06-01 23:19 UTC
When running the Employee Productivity Report, repairs show up twice when using Repair Date criteria.

They first show up when marked as Repaired, and then again when marked as Repaired & Collected.

This stuffs up the numbers when we are tracking how many repairs each tech completes each day.

A repair may have status set to 'Repaired' on Monday, and then the customer picks it up on Tuesday and is then marked as Repaired & Collected. This one ticket will show up in the techs completed repair list for Monday and Tuesday, meaning the Tuesday numbers are higher than what was actually completed.

**Comment by Repairdesk-QA** [comment] 2021-06-02 09:39
Hello @afrahm,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Annie

**Comment by afrahm** [comment] 2021-06-03 23:32
Here is a video showing what I mean.

https://www.loom.com/share/8f239bd9803a4d32a9240537cc1766a8

**Comment by Uzair-RepairDesk** [comment] 2021-06-04 04:51
Thank you @afrahm 

@Repairdesk-QA 
Can you please check this?

**Comment by Repairdesk-QA** [comment] 2021-06-04 08:11
Hey @afrahm! 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Thanks & Regards,
 Annie

**Comment by Repairdesk-QA** [comment] 2021-06-04 09:51
For Internal Use:
https://repairdesk.atlassian.net/browse/RB-3313

**Comment by Repairdesk-QA** [comment] 2021-06-07 11:07
Hey @afrahm !
Thanks for your patience on this issue. I hope you are doing well.

I have been with the development team and get to know that this is not a bug but the current workflow of our system. On **11th May**, the status of ticket **T-12633** has changed to **“repaired”** and on **13th May** its status was updated to **“Repaired and Collected”**. Both of the statuses have the same status type “closed” in our backend and in the Employee productivity report, the results are showing based upon **“closed”** type status. That's why ticket **T-12633** is being displayed **two times** in the report with the status **"Repaired & Collected"**. I hope this will help you.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
Annie

**Comment by afrahm** [comment] 2021-06-07 11:11
It doesn't help at all.. And I assumed that's why it was happening.

Because the report does not show me an accurate number of how many tickets
an employee has completed on a particular day.

How can I show this report then?

Because the way it is currently working is totally useless and I don't know
any use-case of when someone would want it to work like that.

**Comment by Uzair-RepairDesk** [comment] 2021-06-08 05:35
Hi @afrahm 
I can understand your concern. I personally discuss with the engineering team that if it is possible to put a validation. The system should only consider a ticket once it is marked as repaired (status type: completed). We will update this thread if it is technically possible. 

Regards,
Uzair

**Comment by Repairdesk-QA** [comment] 2021-06-28 08:17
Hello @afrahm,
Hope you are doing well.

Sorry for the delay but I have good news for you.
Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.

Thanks!
Quratul Ain

**Comment by afrahm** [comment] 2021-06-29 04:45
@Repairdesk-QA thanks looks like that has resolved the issue.

**Comment by Repairdesk-QA** [comment] 2021-06-29 04:47
Glad you like it.
Closing this issue as it has been fixed
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

Regards,
Quratul Ain

**Closed** 2021-06-29 04:48 UTC
Labels: Customer updated for the fix
