### ISSUE TITLE
Stock Value Wrong

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1468] opened 2021-02-01 02:41 UTC
Stock Value is wrong, i have in the past looked for reason for this and no luck. 
![Capture](https://user-images.githubusercontent.com/60683772/106408732-04094180-640d-11eb-8c5d-ad1e29265fb9.JPG)

**Comment by Shane-RepairDesk** [comment] 2021-02-01 02:42
verified works fine in demo account.

**Comment by Repairdesk-QA** [comment] 2021-02-01 06:45
Hey @Shane-RepairDesk, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards!

**Comment by Repairdesk-QA** [comment] 2021-02-01 07:09
Hey @Shane-RepairDesk,
I hope you are doing well. I have checked the above mentioned scenario and it's working fine on my end. It seems to be an account specific issue. Can you please share your login details with me via email at ayesha.aamer@repairdesk.co, so that I can further investigate this issue.
Thanks & Regards,
Ayesha Aamer

**Comment by mathchouinard** [comment] 2021-02-02 20:25
I have this problem as well, it seems to take a moment for it to update on the inventory page. If I go a couple minutes later after having added items, the new value is updated.

**Comment by Uzair-RepairDesk** [comment] 2021-02-03 04:58
@Repairdesk-QA

**Comment by Repairdesk-QA** [comment] 2021-02-08 07:22
Hey @mathchouinard,
I believe this issue has been fixed in a recent update. Can you give it another try?

Please let me know if there’s anything else I can do for you.

Thanks,
Zain

**Comment by Shane-RepairDesk** [comment] 2021-02-09 19:38
Problem still there.

**Comment by Repairdesk-QA** [comment] 2021-02-10 06:38
Hey @Shane-RepairDesk,
I have checked your concern on our test accounts but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue so we can release a fix during our next release. You can put together a video using Screencastify.

Please let me know if there’s anything else I can do for you.

Thanks,
Zain
![is1](https://user-images.githubusercontent.com/39614480/107474626-81168280-6b94-11eb-992d-25760a3bf28c.png)
![is2](https://user-images.githubusercontent.com/39614480/107474630-8247af80-6b94-11eb-9572-565fa7c00f6c.png)

**Comment by Shane-RepairDesk** [comment] 2021-02-10 15:42
Yeah cool,  i have already supplied a image above nothing has changed..........You can show things work on your side all day long but it does not change that i have and have had multiple problems for long time that are on my build alone.

**Comment by Shane-RepairDesk** [comment] 2021-02-10 15:45
![Capture](https://user-images.githubusercontent.com/60683772/107533537-08f88e80-6b8d-11eb-9064-9bc0641560a7.JPG)
Here is another snippet,  don't really think video will change anything..

**Comment by Repairdesk-QA** [comment] 2021-02-11 07:50
Ok, let me check this again

**Comment by Repairdesk-QA** [comment] 2021-02-16 05:00
Hey @Shane-RepairDesk,
Your reported issue has been assigned to the development team and hopefully, it will be fixed in the next release.

Your patience would be highly appreciated.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment] 2021-02-16 05:01
For internal Use [https://repairdesk.atlassian.net/browse/RB-2638](url)

**Comment by Repairdesk-QA** [comment] 2021-02-16 10:18
Hey @Shane-RepairDesk,

Item 3033 which has serial 9076104617255 has an invalid cost price against it that's why your inventory total is not correct on the Manage products and Inventory summary report, For the time being, we have updated the cost price to zero, you can update the cost price later if you want to. 

Please verify at your end and do let us Know.

Thanks,
Zain

**Closed** 2021-02-18 05:20 UTC
Labels: AVie Pros, Customer Updated - Waiting For further information, Customer updated for the fix, help wanted
