### ISSUE TITLE
Repair Desk Improvement for POS

### ISSUE THREAD

**Issue by Stylemyphones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1628] opened 2021-06-11 17:28 UTC
Hello,

there is a very time consuming issue happening with the POS. 
Each time that a sales representative adds a new item they must scroll back down TWICE since RD scrolls back up automatically each time, not allowing them to change the quantity and the price of the items without having to scroll down each time.

Could this be a disabled feature? Please help!

Thank you in advance and best regards!

**Comment by Repairdesk-QA** [comment] 2021-06-16 05:16
Hello @Stylemyphones,
Hope you are doing well.

I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can **share a video of this issue** or detailed steps so we can release a fix during our next release. You can put together a video **using Screencastify**.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Thanks & Regards,
Quratul Ain

**Comment by Stylemyphones** [comment] 2021-06-16 17:51
Hello @Quratul Ain @Repairdesk-QA ,

Thank you very much for your response and please see the video below.
I hope this helps with understanding and resolving the issue 👍 

https://user-images.githubusercontent.com/83790373/122268219-6d13c200-cea1-11eb-9ff1-d506b7357876.mp4

Best Regards,
Alejandra with StyleMyPhones

**Comment by Repairdesk-QA** [comment] 2021-06-21 08:04
Hi @Stylemyphones ,

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

Thanks!
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-06-21 08:04
For Internal Use:
https://repairdesk.atlassian.net/browse/RB-3404

**Comment by Stylemyphones** [comment] 2021-06-21 18:38
Great news that it is due to a bug and that it can get fixed.

Thank you!

**Comment by isimon179** [comment] 2021-06-22 14:32
if you hold "ctrl" it keeps the search menu open ;)

**Comment by Stylemyphones** [comment] 2021-06-22 18:29
Which search menu do you mean @isimon179?

**Comment by Repairdesk-QA** [comment] 2021-06-23 07:53
Hello @Stylemyphones, 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.

Thanks & Regards,
Quratul Ain

**Comment by Stylemyphones** [comment] 2021-06-23 21:31
AWESOME!
Thank you so much it is working great on our side now.

Best Regards,
Alejandra

**Comment by Repairdesk-QA** [comment] 2021-06-24 04:45
Glad you like it.
Closing this issue as it has been fixed
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

Regards,
Quratul Ain

**Closed** 2021-06-24 06:24 UTC
Labels: Resolved
