### ISSUE TITLE
Device issue is gone when going to edit a ticket

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1809] opened 2022-01-14 20:18 UTC
Whenever I go into EDIT under a ticket to add a device issue, the previous issue I had under the ticket are gone. I need to add it back.

**Comment by Repairdesk-QA** [comment] 2022-01-17 04:34
Hello @techm89,
Hope you are doing well.

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Your patience means a lot to RepairDesk.

_**Regards,**_
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2022-01-18 10:53
Hello **@techm89** ,
Hope you are doing well !

I have checked your concern, I have created a Ticket from Manage Tickets and from POS as well and tries to Edit Device's Issue, the issue is not reproduced. Would be great if you can share a video of this issue or detailed steps to Reproduce. You can put together a video using Screencastify. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out. 

**Note: Kindly share your Business Name associated with Repairdesk Account**

Regards,
**Nida Khalid**

**Comment by techm89** [comment] 2022-01-18 21:02
Here is the link: https://watch.screencastify.com/v/vrjXDRuIpz6zDpEZ1kG3

ALTECH Mobile

Thanks

**Comment by Repairdesk-QA** [comment] 2022-01-19 05:17
Hey **@techm89**,
Hope you are doing well !

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm going to reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Regards, 
**Nida Khalid**

**Comment by Repairdesk-QA** [comment] 2022-01-19 05:23
For internal use 

Jira Link: https://repairdesk.atlassian.net/browse/RB-4472

**Comment by Repairdesk-QA** [comment] 2022-01-21 05:01
Hello **@techm89**,
Hope you are doing well !

I believe this issue has been fixed in recent update. Can you give it another try?
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Video Ref: https://www.screencast.com/t/aULISEVlyz6

**Thanks,**
Nida Khalid

**Comment by Repairdesk-QA** [comment] 2022-01-25 09:35
Hi again @techm89, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Ayesha Aamir

**Closed by Repairdesk-QA** 2022-01-25 09:35 UTC
Labels: Customer updated for the fix
