### ISSUE TITLE
Unable to edit existing customers from POS

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1812] opened 2022-01-24 02:20 UTC
https://www.loom.com/share/3878843844f84ca98899d8cdbdf14f8a

I am able to edit the customer via the customer record in the customer module though, this just happens on the POS

**Comment by Repairdesk-QA** [comment] 2022-01-24 04:40
Hey @afrahm, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by AMott-2020** [comment] 2022-01-24 07:54
> https://www.loom.com/share/3878843844f84ca98899d8cdbdf14f8a
> 
> I am able to edit the customer via the customer record in the customer module though, this just happens on the POS

I am experiencing this same issue aswell.

**Comment by Repairdesk-QA** [comment] 2022-01-25 12:25
Hey @afrahm,
I hope you are doing well. 

I have checked your concern on your account from the backend with one of developer but the issue is not reproduced. Could you please give it another try and let us know if the issue is still occurring so that we can investigate it in detail.

@AMott-2020 could you please share your **Business Name associated with RepairDesk Account** so that we can further look into this issue on your account as well?

**Thanks,**
**Ayesha Aamir**

**Comment by afrahm** [comment] 2022-01-26 22:41
It appears the issue has been fixed.

**Comment by Repairdesk-QA** [comment] 2022-01-28 18:45
Hey @afrahm,
I hope you are doing well.

Glad that the issue has been fixed and working fine for you now.
Closing this issue as it has been fixed.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!
Regards,
Ayesha Aamir

**Closed by Repairdesk-QA** 2022-01-28 18:45 UTC
Labels: Customer Updated - Waiting For further information, customers, POS
