### ISSUE TITLE
Issue with Woocommerce discounts

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1610] opened 2021-05-28 00:42 UTC
Hello,

When the customer is placing an online order thru Woocommerce and they apply a discount coupon, RepairDesk takes the already reduced price and adds another discount.

As an example, this phone's original price is 349.99$, customer applied a 60$ coupon which downs the price to 289.99$. RD then applies another 60$ discount on that 289.99$.

Thanks
![Screen Shot 2021-05-27 at 8 39 39 PM](https://user-images.githubusercontent.com/37091836/119913470-fcc1f280-bf2b-11eb-8162-1a0a2d6405f4.png)

**Comment by Repairdesk-QA** [comment] 2021-06-07 06:10
Hey @antoinegali 

Apologies for late reply.  Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Regards,

**Comment by antoinegali** [comment] 2021-06-08 00:05
Hello,

Thanks!

**Comment by antoinegali** [comment] 2021-06-18 22:03
Hi, any update on this one? Thanks!

**Comment by Uzair-RepairDesk** [comment] 2021-06-21 06:04
@Repairdesk-QA

**Comment by Repairdesk-QA** [comment] 2021-06-21 06:56
Hey @antoinegali,  
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Ayesha

**Comment by Repairdesk-QA** [comment] 2021-06-21 07:00
For internal use:
https://repairdesk.atlassian.net/browse/REP-3220

**Comment by antoinegali** [comment] 2021-07-03 00:27
Hello,

Any update?

Thanks!

**Comment by Repairdesk-QA** [comment] 2021-07-05 05:42
Hey @antoinegali,
I hope you are doing well. 
Sorry for the delayed response. Your reported issue has been assigned to development team and hopefully it will be fixed early next week. Your patience would be highly appreciated.
Thanks, 
Ayesha

**Comment by Repairdesk-QA** [comment] 2021-07-06 06:29
Hello @antoinegali, 
I hope you are doing well. 
We have tried to reproduce the reported issue on our end and everything seems to be working fine. According to the flow the priority is given to the **Item's online price**, if **online price** is not given then priority is given to **item's promotional price** and if **promotional price** is not given the **item's retail price** will be displayed on woo-commerce. Plus in all cases **discount** is applied only **once** against the item but when checkout is done from the website, the invoice will be created in **RepairDesk's Manage Invoices section** and discount will display in the view invoice calculation section instead of displaying against the line item.
Hope it helps and that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks!
Ayesha

**Closed** 2021-07-18 07:56 UTC
Labels: Bug, Customer Updated - Waiting For further information
