### ISSUE TITLE
Cannot Send Emails to Our Domain - Send Invoices or Forgot Password

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#716] opened 2019-03-12 21:40 UTC
![DrPhoneFix Training Pos   Invoice](https://user-images.githubusercontent.com/35181467/54238014-b79d7b80-44ed-11e9-98f8-2ea693ad1926.png)

Still having issue being able to send emails to @drphonefix.com wether from the Email Invoice on Manage Invoices, also tried forgot password on front end trying to log in and no emails, and havent seen to many notifications lately think those are also down

**Comment by Uzair-RepairDesk** [comment] 2019-03-13 11:08
@usmanalikhan93 
Can you please check this?

**Comment by usmanalikhan93** [comment] 2019-03-13 11:40
Sure. Let me check this @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment] 2019-03-13 12:51
@Uzair-RepairDesk Modesto @ochoaonline 

We have verified this issue on our test accounts with gmail domain and it is working fine. However once our CTO will be in office, I will discuss this with him and I or Fahad will update here about the fix/solution.

For internal use:
https://repairdesk.atlassian.net/browse/REP-1639

**Comment by ochoaonline** [comment] 2019-03-13 14:29
@Uzair-RepairDesk @usmanalikhan93  @gmail addresses and all others work on our end as well is just the @drphonefix that has the issue , before i added an IP via whitelist not sure if maybe IP changed or if there's another ip i need to whitelist

**Comment by usmanalikhan93** [comment] 2019-03-26 12:40
Hi Modesto @ochoaonline 

I hope you are doing well. I have checked this with development team and they said your domain @drphonefix.com is rejecting sendgrid mails. I believe Fahad already provided you IP Address (167.89.9.142) so that you can whitelist that.
Please confirm this also check with your domain why it is rejecting this domain.
![image](https://user-images.githubusercontent.com/39614480/54997773-4af6a680-4fee-11e9-92de-93b3f7f42e4d.png)

**Comment by ochoaonline** [comment] 2019-03-27 12:42
I had server team added the IP as whitelist again, can you please test on your end see if it still gives you same error Thanks and i'll test invoices on my end

**Comment by usmanalikhan93** [comment] 2019-03-27 12:59
Hi @ochoaonline 

Let me check this tomorrow and will revert back to you with information.

**Comment by usmanalikhan93** [comment] 2019-04-03 12:55
Hi Modesto @ochoaonline 

We are still getting this error. I have reconfirmed from our CTO. Please check this at your domain end. 

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment] 2019-04-10 05:26
Hi Modesto @ochoaonline 

Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali.

**Closed by usmanalikhan93** 2019-04-10 05:26 UTC
Labels: Customer Updated - Waiting For further information, DrPhoneFix, help wanted
