### ISSUE TITLE
Pre repair device condition is not getting saved 

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1675] opened 2021-08-06 09:48 UTC
After generating the ticket, the pre repair device condition is not getting populated on ticket while printing.

**Comment by alliedcomputers** [comment] 2021-08-06 09:53
https://user-images.githubusercontent.com/87709069/128492830-ea76120e-b2d0-4b62-bcc4-6ef898a0f333.mp4

Please find the video

**Comment by Repairdesk-QA** [comment] 2021-08-06 13:03
Hey @alliedcomputers
Azka here. 
I hope you are doing well.
Thank you for bringing this to our attention. It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as the issue is fixed.
Thanks & Regards

**Comment by Repairdesk-QA** [comment] 2021-08-06 13:03
For internal use only:
https://repairdesk.atlassian.net/browse/RB-3620

**Comment by Repairdesk-QA** [comment] 2021-08-09 06:47
Hey @alliedcomputers 
I hope you are doing well.
I really appreciate that you took the time to share your problem. I believe this issue has been fixed in recent update. Can you give it another try?
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards
Azka

**Comment by Repairdesk-QA** [comment] 2021-08-11 05:00
Hey again
Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards
Azka

**Closed by Repairdesk-QA** 2021-08-11 05:00 UTC
Labels: Customer updated for the fix
