### ISSUE TITLE
Problems with trade-in module

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1515] opened 2021-02-25 17:17 UTC
We sometimes have issues with the trade-in module in a weird way. For example: if we need to take back a trade-in device we have placed on a ticket. Sometimes it gets back in stock without problems, other times we have to contact the support to make them get it back in stock through the backend. Yesterday we had a device that by et self had put itself in pending refurbish status. And we had to get the support to bring it back in stock. What is the issue? And how can we be able to fix those issues our self?

**Comment by Repairdesk-QA** [comment] 2021-02-26 06:32
Hey @jphansendk, 
Ayesha here. Can you please elaborate on your concern? How you exactly use the trade-in module at this point in time? Will be happy to advise you once you share additional details.
Thanks!

**Comment by jphansendk** [comment] 2021-02-26 08:30
Sure. Our workflow is as follows. We receive an order via API on a repair from our client (Insurance agency). We add a matching refurbished device to the ticket from the trade-in module and ship this device to the customer. When the customer receives the refurbished device they return the damaged device to us in the same box. Normally we then add the damaged device to the trade-in module and make a refurbish ticket. Sometimes we need to remove the added device from the ticket again. Maybe the customer rejected the parcel or other things go wrong. Maybe we receive a device we have shipped to the customer earlier and they broke this device. The device is still attached to the "old" ticket, and the status is sold in trade-in. But we need to get it away from this "old" ticket and need to put it on a new refurbish ticket. Sometimes it's no problem. Other times the device is stuck in sold status even though we remove it from the "old" ticket. In that case, I need to contact RD support and make them set the status back to "in stock" via the backend as I understand it? Does this make sense?
We are not using RD fully yet concerning pricing the devices and so on. This is because we have to make everything we do in RD work on an external system via API as well. Hope this makes sense?

**Comment by Repairdesk-QA** [comment] 2021-06-08 12:05
Hi @jphansendk 
I hope you are doing well. Sorry for the delay but I was pulled away and caught up with work. I have checked your concern but unfortunately, I am unable to reproduce your issue. Could you please connect with one of our support agent on live chat so that he can look into the issue you are facing in detail. 
Thanks!

**Comment by jphansendk** [comment] 2021-06-08 12:12
Haha.. Well that's what I do everytime.. And the problem still appear.. That's why I wrote in here to report the big. The only way support can help is to correct the error through the backend.. But that is a waist of time for all of us.. Would be 200% better to get the problem sorted out once and for all.. Seriously we are in contact with the live support several times a week because of this and need to wait 1-2 days to get it corrected.. That's a problem when devices are stuck in the system for days

**Comment by Repairdesk-QA** [comment] 2021-08-30 04:37
Hello @jphansendk,
Hope You are doing well.

I would like to tell you that there is another way of doing tradeIn back to Repairdesk.
For such tradeIn items(you want them back to inventory), you can use Custom Status. When you mark custom status against a tradeIn and that tradeIn used in a ticket. After deleting that tradeIn from ticket, you will be able to see that instock.

You can set custom status from
Store Settings->Order Status-> Trade In Status-> Add new from (+status)

For more details please have this video:
https://www.screencast.com/t/Ux5cmgpIaWs

**Comment by jphansendk** [comment] 2021-08-30 06:17
> Hello @jphansendk,
> Hope You are doing well.
> 
> I would like to tell you that there is another way of doing tradeIn back to Repairdesk.
> For such tradeIn items(you want them back to inventory), you can use Custom Status. When you mark custom status against a tradeIn and that tradeIn used in a ticket. After deleting that tradeIn from ticket, you will be able to see that instock.
> 
> You can set custom status from
> Store Settings->Order Status-> Trade In Status-> Add new from (+status)
> 
> For more details please have this video:
> https://www.screencast.com/t/Ux5cmgpIaWs

hmm.. So what does this do, compared to the way we do it? The only change I see is that he changes the status to "sold to customer" before adding it to the ticket? Does this change how the system sees it when you remove it again?

**Comment by Repairdesk-QA** [comment] 2021-08-30 06:28
> > Hello @jphansendk,
> > Hope You are doing well.
> > I would like to tell you that there is another way of doing tradeIn back to Repairdesk.
> > For such tradeIn items(you want them back to inventory), you can use Custom Status. When you mark custom status against a tradeIn and that tradeIn used in a ticket. After deleting that tradeIn from ticket, you will be able to see that instock.
> > You can set custom status from
> > Store Settings->Order Status-> Trade In Status-> Add new from (+status)
> > For more details please have this video:
> > https://www.screencast.com/t/Ux5cmgpIaWs
> 
> hmm.. So what does this do, compared to the way we do it? The only change I see is that he changes the status to "sold to customer" before adding it to the ticket? Does this change how the system sees it when you remove it again?

This will help your tradeIn items to go back to inventory.
It would be great if you try this flow.
I hope this will solve your problem and if you still have any questions/issues, please let us know.
It's pleasure for us to assist you

Regards,
Quratul Ain

**Comment by jphansendk** [comment] 2021-08-30 06:33
> > > Hello @jphansendk,
> > > Hope You are doing well.
> > > I would like to tell you that there is another way of doing tradeIn back to Repairdesk.
> > > For such tradeIn items(you want them back to inventory), you can use Custom Status. When you mark custom status against a tradeIn and that tradeIn used in a ticket. After deleting that tradeIn from ticket, you will be able to see that instock.
> > > You can set custom status from
> > > Store Settings->Order Status-> Trade In Status-> Add new from (+status)
> > > For more details please have this video:
> > > https://www.screencast.com/t/Ux5cmgpIaWs
> > 
> > 
> > hmm.. So what does this do, compared to the way we do it? The only change I see is that he changes the status to "sold to customer" before adding it to the ticket? Does this change how the system sees it when you remove it again?
> 
> This will help your tradeIn items to go back to inventory.
> It would be great if you try this flow.
> I hope this will solve your problem and if you still have any questions/issues, please let us know.
> It's pleasure for us to assist you
> 
> Regards,
> Quratul Ain

But my only concern is that we do all this via API. The trade-in device is automatically added to the ticket via API, so I don't see how we can do this via the API?

**Comment by Repairdesk-QA** [comment] 2021-08-30 07:10
> > > > Hello @jphansendk,
> > > > Hope You are doing well.
> > > > I would like to tell you that there is another way of doing tradeIn back to Repairdesk.
> > > > For such tradeIn items(you want them back to inventory), you can use Custom Status. When you mark custom status against a tradeIn and that tradeIn used in a ticket. After deleting that tradeIn from ticket, you will be able to see that instock.
> > > > You can set custom status from
> > > > Store Settings->Order Status-> Trade In Status-> Add new from (+status)
> > > > For more details please have this video:
> > > > https://www.screencast.com/t/Ux5cmgpIaWs
> > > 
> > > 
> > > hmm.. So what does this do, compared to the way we do it? The only change I see is that he changes the status to "sold to customer" before adding it to the ticket? Does this change how the system sees it when you remove it again?
> > 
> > 
> > This will help your tradeIn items to go back to inventory.
> > It would be great if you try this flow.
> > I hope this will solve your problem and if you still have any questions/issues, please let us know.
> > It's pleasure for us to assist you
> > Regards,
> > Quratul Ain
> 
> But my only concern is that we do all this via API. The trade-in device is automatically added to the ticket via API, so I don't see how we can do this via the API?

There might be some issues with your Payload of API because we are not facing any issues with our flow.
You can see in this video:
https://www.screencast.com/t/1sHyQxjen5

Can you please share your **Payload of API without HEADER INFORMATION** so we can see where's the issue.
If you are not comfortable sharing your information on git, you can share your details via our support agents.

Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-09-03 06:16
Hello @jphansendk,
Hope you are doing well.

Your reported issue has been assigned to the development team and hopefully, it will be fixed in our next week.
Your patience would be highly appreciated.

Thanks & Regards!
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-09-03 06:17
For Internal Use Only: 
https://repairdesk.atlassian.net/browse/RB-3742

**Comment by Repairdesk-QA** [comment] 2021-09-09 13:27
Hey @jphansendk 
I hope you are doing well.
I hope your issue has been fixed in reference to your whatsapp conversation with Mr. Saif Ali. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out. 
Thanks & Regards
Azka.

**Comment by Repairdesk-QA** [comment] 2021-12-07 10:20
Hi again @jphansendk, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Thanks,
Ayesha Aamir

**Closed by Repairdesk-QA** 2021-12-07 10:20 UTC
Labels: Bug, Assigned to developer, Trade-In Module
