### ISSUE TITLE
Tradein automatic change from sold to in stock 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#509] opened 2018-11-13 21:00 UTC
Hello,
Several trade in this put "in stock" without us having modified them. See example in attachment.
Exemple #8550
<img width="947" alt="8550" src="https://user-images.githubusercontent.com/40500094/48442740-0e23c480-e75d-11e8-9335-603ed38264b4.png">
<img width="944" alt="8550 history" src="https://user-images.githubusercontent.com/40500094/48442742-10861e80-e75d-11e8-8771-ffdfbe81e3e1.png">

Exemple #8340
<img width="945" alt="8340" src="https://user-images.githubusercontent.com/40500094/48443032-e2550e80-e75d-11e8-9471-6eacc562076d.png">
<img width="935" alt="8340 history" src="https://user-images.githubusercontent.com/40500094/48443038-e54fff00-e75d-11e8-8514-038132734357.png">

--
french:
Bonjour,
Plusieurs trade in ce mettent "in stock" sans que nous les ayons modifié. Voir exemple en pièce jointe.

**Comment by Uzair-RepairDesk** [comment] 2018-11-14 06:29
Hi @JessicaSOS 
Your last screenshot of admin history for an item "#8430" depicts that after its sold you made a refund and while refunding the item, you sent it back to the inventory. When an item comes back in the stock, its status automatically becomes "In Stock" if you don't mark it "Faulty" specifically. 
Check screenshots attached for your understanding. 
Please verify it at your end and please do let me know if an issue is still there. Thanks

![48443038 e54fff00 e75d 11e8 8514 038132734357 png 1869x856](https://user-images.githubusercontent.com/22955861/48464098-1aad2900-e800-11e8-84ed-b06c23badcba.png)
![uzairshah pos 4](https://user-images.githubusercontent.com/22955861/48464099-1b45bf80-e800-11e8-9129-a9b1a9ef5830.png)

**Comment by JessicaSOS** [comment] 2018-11-15 17:21
For item # 8340:
I understand what you said but, it went from "pending refurb" to "in stock" without any adjustment.

  And for item # 8550?

I also have another example: # 8828 (sold in January 2018), # 8822 (sold in May 2018), # 8811 (sold in March 2018), # 8804 (sold in February 2018), etc.
I had to go change the status from "in stock" to "sold" myself, manually.

And yesterday is Wednesday the 14th of november, about 5 items per store were manually put in stock without any adjustment!

**Comment by Uzair-RepairDesk** [comment] 2018-11-21 04:32
@usmanalikhan93 
Please review it in detail from Jessica account and it will be appreciated if you can find out the issue. Thanks

**Comment by usmanalikhan93** [comment] 2018-11-21 05:49
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment] 2018-12-13 06:34
Hi @JessicaSOS 

I have reviewed your concern on my test account but I was unable to reproduce the issue on my end. Can you help me more to replicate this ?

**Comment by JessicaSOS** [comment] 2018-12-13 21:07
I do not know how to reproduce it ... I gave you some example mentioned above. I can let you know if I see this problem again soon ...

**Comment by usmanalikhan93** [comment] 2019-01-21 04:32
Hi @JessicaSOS 

If you face this issue again in future you can open this task. For now I am closing this.

**Closed by usmanalikhan93** 2019-01-21 04:32 UTC
Labels: Customer Updated - Waiting For further information, Unable to reproduce, help wanted
