### ISSUE TITLE
Xero Integration - automatically populate account on invoices

### ISSUE THREAD

**Issue by Adski01** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1563] opened 2021-04-09 12:34 UTC
At the moment, the RepairDesk-Xero integration creates invoices in Xero once they are created in RepairDesk.  It creates the invoices but does not populate the account field automatically.    We would like this field to automatically populate based on the account integration chosen for the various types of Sales accounts. 

![image](https://user-images.githubusercontent.com/80407173/114180408-108fa600-9938-11eb-9cb0-03e3cebc2d22.png)
![image](https://user-images.githubusercontent.com/80407173/114180434-17b6b400-9938-11eb-8222-9666b627b8fb.png)
 
So above you can see the draft invoice in Xero and the RepairDesk Xero Integration.  The invoice shows the sale of some inventory goods and we want the Account (red rectangle) to be populated with the '100J - Counter Sales' Account

**Comment by Adski01** [comment] 2021-05-04 13:46
Please can I have an update?  This needs to be addressed because this should be core functionality

**Comment by Uzair-RepairDesk** [comment] 2021-05-05 08:29
Hi @Adski01 
Hope you are doing well. Thank you for your follow-up. We have already marked it under enhancements of "Xero Integration". We will check the feasibility to add this option once we proceed to update Xero integration. Thanks. 

Regards,
Uzair

**Comment by Adski01** [comment] 2021-05-05 11:01
That is good thank you Uzair.  When will the change be made?  We have worked with many other Xero integrations on other Cloud Apps and this function is normally standard functionality.

**Comment by Uzair-RepairDesk** [comment] 2021-05-07 06:58
Hi @Adski01 
I am not able to give you a timeline at this moment. Our criteria are that we add requests in our backlog and pick up the improvements based on the number of requests of our community. 

We have added it to our backlog and we will pick it up once we plan the improvements of Xero integration. Thanks

**Comment by Adski01** [comment] 2021-05-07 11:55
Thanks for your response. How long is the backlog?  How many items will be dealt with before this one?

This is core functionality for a Xero integration.  This could reflect poorly in the Xero App Marketplace for any reviews that your customers or their accountants leave so I’m trying to help you make your Xero integration isn’t a reason why you lose customers or don’t gain potential customers.

Hi Shafia, hope you’re doing well.  When you and I spoke about the Xero integration during our pre sales chats, we talked about the maturity of the RepairDesk  / Xero integration and unfortunately, it’s not what we expected of a mature integration.  We’re finding out now that the integration also does not synchronise Purchase Orders from RepairDesk to Xero.  This is going to cause huge amounts of manual work to be required in Xero when this also should be core functionality.   The only reason I mention this is so you can warn potential customers of the extra manual work they’ll have to do.

Kind regards,

Adam Smith HNDip
Technology Consultant

(t) 01534766233
(m) 07797799060
---------------------------------------------------------------------
***@***.***D7433F.DD2EA020]
http://www.purpose.je/
Linkedin<http://www.linkedin.com/pub/luke-smith/10/a00/a19>
Watch our Video<https://vimeo.com/90128098>

**Comment by Uzair-RepairDesk** [comment] 2021-05-10 08:36
Hi @Adski01 
I will update you once we plan and cater to this request. 

Thanks for helping us make this a platform you'll depend on. 

Regards,
Uzair

**Comment by Adski01** [comment] 2021-05-11 13:21
Unfortunately I doubt that the system will be depended on, unless we know when this functionality will be planned.


Adam Smith HNDip
Technology Consultant

(t) 01534766233
(m) 07797799060
---------------------------------------------------------------------
***@***.***D74670.DD7E91A0]
http://www.purpose.je/
Linkedin<http://www.linkedin.com/pub/luke-smith/10/a00/a19>
Watch our Video<https://vimeo.com/90128098>

**Comment by Adski01** [comment] 2021-06-16 10:32
How long will we wait for a response on this?  What would it cost to complete changes to the Xero integration within 3 weeks?

**Comment by HeisenbergTech** [comment] 2021-09-14 01:02
Hi Adski01,

How did you go with this mate? we too are finding that the Xero integration is not what was promised/expected

**Comment by Adski01** [comment] 2021-09-14 09:51
Hi @HeisenbergTech, a fellow Xero user - your support on this would be most welcome!  

After months of chasing, the RepairDesk development team finally seem to be listening.  We're now about to start talks about the changes/enhancements we want.  I've got a bunch of ideas about what should be done but I think it would be good for you to add your expectations as you may have thought of things we have not?   We want to do the above and populate the account field based on the account chosen in the RepairDesk integration setup, but we also want the Xero integration to be enhanced by allowing more than 1-time syncs (which it currently does) - to explain further, when an invoice is created in RD, it syncs to Xero, but if the Invoice is then changed in RD, nothing changes in Xero.  In our business, invoices are not generally paid at the time of purchase/creation and we regularly have changes to the invoices after creation.  This means that a lot of manual work currently has to be done in Xero including reconciliation between the two systems.   RD Dev Team are now asking me to detail the exact technical enhancements I want so do feel free to mention anything you think might also be useful.

**Comment by Repairdesk-QA** [comment] 2021-09-16 08:18
Hello @Adski01,
Hope you are doing well.

I have checked your concern but I am unable to reproduce this issue as I am having Account details.
Please have this image for your reference:
![image](https://user-images.githubusercontent.com/39614480/133576532-be4dbdd3-ad70-4b5e-b9b4-a999926bfc41.png)

Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-10-11 11:13
Hello @Adski01,
Hope you are doing well.

I am glad that your issue has been fixed.
Closing this issue as it has been fixed.
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

**Regards,**
Quratul Ain

**Closed** 2021-10-11 11:14 UTC
Labels: enhancement, Resolved, Xero Integration, customer updated
