### ISSUE TITLE
Email Status  BOUNCE

### ISSUE THREAD

**Issue by KEZSVS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1750] opened 2021-11-01 15:01 UTC
Please if can someone fix this issue ASAP when I send emails to customers or to the team emails bunce, this problem continues for the last few weeks no one help me on the phone and also remotely 

So please let me see if someone from the development team can help me with this 

![Capture](https://user-images.githubusercontent.com/69765024/139692874-0a9809c8-9e63-47a9-8a05-8b72c7fc4f1b.PNG)

**Comment by Repairdesk-QA** [comment] 2021-11-05 07:40
Hello @KEZSVS,
Hope you are doing well.

Can you please elaborate on your concern? 
**_Are you sending the emails manually? or issue is in Auto sending the email?_**
Would be great if you can answer the above questions or share a video of this issue or detailed steps so we can release a fix during our next release. **_You can put together a video using Screencastify._**
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by KEZSVS** [comment] 2021-11-05 12:17
manually
Here you go 

https://www.awesomescreenshot.com/video/5905850?key=82d628515ab6cfbf403bf7988a412af1

**Comment by Repairdesk-QA** [comment] 2021-11-08 06:35
Hello @KEZSVS,
Hope you are doing well.

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed in our next release.
Your patience would be highly appreciated.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-11-08 06:35
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4064

**Comment by Repairdesk-QA** [comment] 2021-11-09 11:47
Hello @KEZSVS,
Hope you are doing well.

Your reported issue has been discussed with our Development Team & they've found the issue is not from our end.
DMARC establishes a method for a domain owner to Publish its email authentication practices.
Please ask your domain registrar and get it disabled.
I hope this will solve your problem & if not, kindly let us know.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-11-22 07:55
Hello @KEZSVS,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain

**Closed** 2021-11-22 07:55 UTC
Labels: Customer updated with workaround
