### ISSUE TITLE
Transfer serialised items issues

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#85] opened 2016-11-05 06:07 UTC
We transferred one serialised item today to another store and select the correct Serial. The item actually transferred successfully to that store but the stock Status in the original store is still showing as In Stock.
In that receiving store, the stock got increased 1 but it does not showing up the Serial number of that item. When we tried to create the Serial, the system complaint about the Serial is already in used.

<img width="1277" alt="screen shot 2016-11-05 at 5 01 02 pm" src="https://cloud.githubusercontent.com/assets/22993605/20028037/3995eacc-a37a-11e6-96cb-637137f24750.png">
<img width="1269" alt="screen shot 2016-11-05 at 5 03 03 pm" src="https://cloud.githubusercontent.com/assets/22993605/20028038/3a2d614a-a37a-11e6-9d97-1252d455d342.png">

**Comment by Repair-Desk** [comment] 2016-11-06 11:27
@HafizAnas please review and assign it to @muhammadfayyaz3

**Comment by HafizAnas** [comment] 2016-11-07 11:15
Hi @quangc 

Sorry for inconvenience. I have reviewed this issue but I am not able to reproduce at my end. Please refresh the page,  once employee of other store received the inventory. I hope it will be fine at your side as well after doing this.
Do let me know or share steps with me if you are still facing this issue.

**Comment by quangc** [comment] 2016-11-10 00:06
So if an item with serial is transferred to another store, will it disappeared from original store or simply showing some Status?

**Comment by Repair-Desk** [comment] 2016-11-14 02:54
@Uzair-RepairDesk Can you update @quangc?

**Comment by quangc** [comment] 2016-11-14 03:47
As far as I can inform your team. Every time we transfer serialised items to another store. We do have  the ability to select which serials to transfer but those items, after got transferred   to another store the serials do not come over. The quantity does increased, but no serials are created. And in the original store, they are still showing as in stock.

Not sure how your team can get them transferred  correctly, we still cannot do it.

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by Repair-Desk** [comment] 2016-11-14 03:49
@HafizAnas can you review above scenario?

**Comment by Uzair-RepairDesk** [comment] 2019-02-14 07:32
we fixed this issue already. Closing this post.

**Closed by Uzair-RepairDesk** 2019-02-14 07:32 UTC
Labels: help wanted
