### ISSUE TITLE
Cost not updated  correctly on estimates when new products are used - see details

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1785] opened 2021-12-20 19:21 UTC
1) I created a PO and created a new part on the PO -I did not enter a cost price when the new product was created but put the cost on the PO (point one maybe you should update the part cost to the PO amount when the PO is created)
2) I created an estimate using this new sku
3) I created a GRN.  At this time  the product unit cost is updated to the cost received on the PO
4) I approve the estimate  and invoice it
5) The invoice shows 100% profit because it invoiced it as if the cost amount was zero because that is what the cost was when the estimate was created.  It didn't seem to look at the part number to get the current cost

**Comment by Repairdesk-QA** [comment] 2021-12-21 05:18
**Hello @AbbyCSC,**
**I hope you are doing well.** 
 
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using **Screencastify**.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Thanks,_**
**_Ayesha Aamir_**

**Comment by AbbyCSC** [comment] 2021-12-21 14:17
I was able to duplicate this doing exactly what I outlined which is why I reported it as a bug.  I don't have time to create a video but will try to do it next week.  As I have a work around you can close this if you wish.
Thank you
Abby

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment] 2021-12-22 10:03
Hello @AbbyCSC,
Hope you are doing well.

We totally understand your time. We are closing this for now as we have to keep the record but you can open this task and share the video anytime at your convenience.

Would love to hear back from you soon!

**_Thanks & Regards,_**
Quratul Ain

**Closed** 2021-12-22 10:04 UTC
Labels: Customer Updated - Waiting For further information, Purchase Order, Unable to reproduce
