### ISSUE TITLE
transferred tradein phone

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#684] opened 2019-02-21 19:10 UTC
A tradein item has been transferred from store # 1 to store # 2. Several days later, he was transferred from store # 2 to number # 1. Still, I can not see the item in store # 1. See example item # 10221.
<img width="947" alt="10221" src="https://user-images.githubusercontent.com/40500094/53194685-f96b8e00-35e1-11e9-8e25-c56bf4337697.png">
<img width="940" alt="10221 search" src="https://user-images.githubusercontent.com/40500094/53194825-4ea79f80-35e2-11e9-8d1f-ccb8928fe3ce.png">

_--
french:
Un item tradein a été transéfér du magasin #1 vers le magasin #2. Plusieurs jours plus tard,  il a été transféré du magaisn #2 vers le numéro #1. Pourtant, je suis incapable de visualisé l'item dans le magasin #1. Voir exemple item #10221._

**Comment by usmanalikhan93** [comment] 2019-02-22 04:37
Hi @JessicaSOS 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment] 2019-02-22 05:26
Hi @JessicaSOS 

I have reviewed in your account. It is present in store 1(Limoilou). Please have a look on screenshot.
![jessica_trade_in_transfer](https://user-images.githubusercontent.com/39614480/53221676-4d32b180-368c-11e9-9c71-2108b0b8a0c8.png)

**Comment by usmanalikhan93** [comment] 2019-02-25 06:24
Hi again @JessicaSOS   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment] 2019-02-26 16:59
It was impossible to view it from SOS Phone Limoilou. I do not know what you have changed but actually, it works in itself. There was another item that I was not able to view at Limoilou (the main store) but I did not notice it. I'll let you know if the problem comes back.
Have a good day

**Comment by JessicaSOS** [comment] 2019-02-26 21:20
I find another example. Item # 10438 is not visible in Limoilou. It is "in stock" in Lévis but I do not see it in the list of devices "in stock" of Lévis.

**Comment by usmanalikhan93** [comment] 2019-02-27 04:39
Sure. Let me check this.

**Comment by usmanalikhan93** [comment] 2019-02-27 07:54
Hi @JessicaSOS 

I have test this on my test account and it works according to the flow. Can you help me to reproduce this issue ? I saw some abnormal behavior in admin history. It will be very helpful for me if you tell me how did you transfer this item.

**Comment by JessicaSOS** [comment] 2019-02-28 17:35
The device has not been transferred differently than usual. It looks like this problem occurs when a device is transferred more than once. I do not know exactly where the problem comes from so I can not help you any more. Try to make several transfers and maybe change the status. You have to test ...

**Comment by JessicaSOS** [comment] 2019-02-28 17:42
other exemple: #11248

**Comment by JessicaSOS** [comment] 2019-02-28 17:47
By changing the status, it does not change anything. Maybe this happens when an item has been sold and is transferred again after a return to inventory?

**Comment by Uzair-RepairDesk** [comment] 2019-03-01 06:44
@usmanalikhan93

**Comment by usmanalikhan93** [comment] 2019-03-01 07:19
Hi @JessicaSOS 

Ok let me try to reproduce this on my end. Thanks for information.

**Comment by usmanalikhan93** [comment] 2019-03-13 11:31
Hi @JessicaSOS 

Your reported issue has been fixed. But there is one thing the old records needs to be update manually. So if you know the items which were transferred and not showing, you can mention here there transfer order and our developer will check that and fix those.

**Comment by JessicaSOS** [comment] 2019-03-13 15:42
Here are the items I spotted:
# 12060 - K4 2017 which is in Longueuil (which I have not been able to put in a bill)
# 10438 - S7 of levis that is in stock but not seen
# 11248 - G5 to Limoilou which always appears transfered in over.

--
 Voici les item que j'ai repéré:
#12060 - K4 2017 qui est à Longueuil (que je n'ai pas été en mesure de mettre dans une facture)
# 10438 - S7 de lévis qui est in stock mais qu'on ne voit pas.
#11248 - G5 à Limoilou qui apparait toujours transfered en over.

**Comment by usmanalikhan93** [comment] 2019-03-14 05:50
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1651

**Comment by JessicaSOS** [comment] 2019-03-18 14:02
Hello,
I hope this problem is solved for the future. For now, the devices cited in issue # 684 are all fixed.
Thank you

**Comment by JessicaSOS** [comment] 2019-03-18 17:29
#11869 make the same thing...

**Comment by usmanalikhan93** [comment] 2019-03-19 09:32
Hi @JessicaSOS 

Can you tell us in which store it should be ? #11869

**Comment by JessicaSOS** [comment] 2019-03-19 12:42
the item does not appear in transfered when we connect to the Limoilou store. It's as if he never existed, no result. However, the device has been transferred to Lévis and is now in stock in Lévis.
--
l'item n’apparait pas en transfered lorsque nous somme connecter dans le magasin de Limoilou. C'est comme s'il n'avait jamais existé, aucun résultat. Pourtant, l'appareil a été transféré à Lévis et est maintenant in stock à Lévis.

**Comment by usmanalikhan93** [comment] 2019-04-03 12:58
Hi @JessicaSOS 

We have done as you said about #11869. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Closed by usmanalikhan93** 2019-04-03 12:58 UTC
Labels: Customer Updated - Waiting For further information, SOS Phone, help wanted

**Comment by JessicaSOS** [comment] 2019-04-03 15:50
fixed for all phone mentionned here
