### ISSUE TITLE
Possible Bug Causing Problems

### ISSUE THREAD

**Issue by Stylemyphones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1643] opened 2021-06-23 21:26 UTC
Hello,

We are having issues with the POS due to the products being added first and then the customer says, "oh! I have a tax-ID" which would make them tax exempt.

If the customer is added after the products, the items are not updating without taxes, or vice versa with taxes if we discover that the tax permit is inactive.

We then have to take the time to go into each product and manually mark the item tax exempt.

PLEASE HELP!

Best Regards,
Alejandra at SP.

**Comment by Repairdesk-QA** [comment] 2021-06-24 12:58
Hey @Stylemyphones 
Hope you are doing well.
Azka here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks.

**Comment by Repairdesk-QA** [comment] 2021-06-25 07:58
Hey @Stylemyphones 
I hope you are doing great.
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Azka

**Comment by Stylemyphones** [comment] 2021-06-25 17:44
Thank you!
Here you are,

https://user-images.githubusercontent.com/83790373/123464907-0a15df80-d5b3-11eb-9553-8edd9ee0bd5b.mp4

**Comment by Repairdesk-QA** [comment] 2021-06-28 08:23
Hey @Stylemyphones!
Hope you are doing well.
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as it is fixed.
Thanks!
Azka

for internal use only:
https://repairdesk.atlassian.net/browse/RB-3443

**Comment by Stylemyphones** [comment] 2021-06-28 18:41
Thank you so much, looking forward to hearing back.

**Comment by Repairdesk-QA** [comment] 2021-07-01 13:54
hey @Stylemyphones 
hope you are doing well.
I believe this issue has been fixed in recent update. Can you give it another try?
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks & Regards.
Azka

**Closed** 2021-07-09 06:06 UTC
Labels: Customer updated for the fix

**Comment by Stylemyphones** [comment] 2021-07-09 17:59
Yes, thank you so much!
It is indeed fixed now.

Best Regards.
