### ISSUE TITLE
Invoice Date Disappearing From Tickets In POS Screen

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1755] opened 2021-11-09 07:01 UTC
When clicking on the Month and Year in Grey at the top of the box and then selecting a different year and month, the box disappears and nothing is changed. 
Makes it time consuming to add a date that was even just a year ago as you have to keep clicking the arrows next to the month and date.

![image](https://user-images.githubusercontent.com/91883389/140877132-d05025c8-d07a-4843-b6ce-b67111df3048.png)

**Comment by Repairdesk-QA** [comment] 2021-11-10 06:28
Hello @AVECorp,
Hope you are doing well.

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Your patience means a lot!

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-11-10 07:24
Hi again @AVECorp,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can **_share a video_** of this issue or detailed steps so we can release a fix during our next release. You can put together a **_video using Screencastify._**
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by AVECorp** [comment] 2021-11-11 02:14
Hi Quratul, Here is a video of the fault.This is a custom date field we are using in our ticket entry processes. https://watch.screencastify.com/v/YfoaPgK8ioW6KxzaCsWt Ben Rawnsley | Wholesale ManagerPhone: +61 3 9706 5325 | Email:  ***@***.***: 318 Hammond Road, Dandenong South, VIC 3175, AustraliaVisit us online | www.avecorp.com.au From: Repairdesk-QASent: Wednesday, 10 November 2021 6:24 PMTo: Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTSCc: AVECorp; MentionSubject: Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Invoice Date Disappearing From Tickets In POS Screen (Issue #1755) Hi again @AVECorp,I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.Regards,Quratul Ain—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  Message protected by MailGuard: e-mail anti-virus, anti-spam and content filtering.https://www.mailguard.com.auReport this message as spam    Message  protected by MailGuard: e-mail anti-virus, anti-spam and content filtering.https://www.mailguard.com.au

**Comment by Repairdesk-QA** [comment] 2021-11-11 07:43
Hello @AVECorp,
Hope you are doing well.

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-11-11 07:43
**_For internal use only:"_**https://repairdesk.atlassian.net/browse/RB-4087

**Comment by Repairdesk-QA** [comment] 2021-11-24 04:37
Hello @AVECorp,
Hope you are doing well.

Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.
Waiting for your feedback.

**_Regards,_**
Quratul Ain

**Closed** 2021-12-02 12:41 UTC
Labels: Bug, Resolved, Customer updated for the fix
