### ISSUE TITLE
Tickets Not Closing 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1211] opened 2020-07-13 17:50 UTC
Hello, 

I had brought up an issue regarding the tickets not closing. And it was closed? The issue still the same. When ever we check check out for a Unlocking service the ticket remains open altho its already repaired and collected. 

The following tickets have invoices and have already paid for but haven't being automatically closed. T-1118 / T-1114 / T-1110 / T-1095 / T-1063 / T-1009

**Comment by MuhammadAdnan32** [comment] 2020-07-14 04:34
Hi @Omar1892 ,
Can you please share your updated credentials in PM on adnan@repairdesk.co?
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment] 2020-07-15 17:05
@MuhammadAdnan32  They have being sent via email

**Comment by MuhammadAdnan32** [comment] 2020-07-16 04:05
Hi @Omar1892 ,
Received and thank you for sharing.

**Comment by MuhammadAdnan32** [comment] 2020-07-17 10:20
Hi @Omar1892 ,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Kindly see the attached video also:https://drive.google.com/file/d/17BfKLadxUnMsJyNqicXcxVHjtcMUDsei/view
 Would be great if you can share a video of this issue so we can release a fix during our next release.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
M Adnan

**Comment by Omar1892** [comment] 2020-07-17 16:20
@MuhammadAdnan32  Video was sent to adnan@repairdesk.co - check my account so that you can see how many tickets we have opened. The issue might not happen on your account, but its happening to us. The issue is there.

**Comment by MuhammadAdnan32** [comment] 2020-07-20 09:52
Hi @Omar1892 ,
Can you please allow me to create a ticket and invoice on your account for testing this issue?

**Comment by Omar1892** [comment] 2020-07-20 16:33
Yes, please go for it. If it doesn't work on the first try do it multiple times. The issue is there.

**Comment by MuhammadAdnan32** [comment] 2020-07-21 04:48
Ok, thank you. I will look into this and circle back to asap.

**Comment by MuhammadAdnan32** [comment] 2020-07-21 10:46
Hi @Omar1892 ,
I have checked your concern on your account with multiple tickets but unfortunately, I am unable to reproduce your issue. Would be great if you can share detailed steps of the issue whenever you will face the same issue. 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
M Adnan

**Comment by Omar1892** [comment] 2020-07-24 16:18
@MuhammadAdnan32 Would you mind checking this tickets are reference T-1118 / T-1114 / T-1110 / T-1095 / T-1063 / T-1009 this tickets were paid for but were never closed. The issue only happens on the unlocking sections. It hasn't happen on any other place with in the system aside from the unlocking.

**Comment by Repairdesk-QA** [comment] 2021-12-10 06:38
Hello @Omar1892,
Hope you are doing well.

We sincerely apologize for the inconvenience and we have released a fix for this issue. Can you please confirm if you are still getting the same issue?
Waiting for your response.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment] 2021-12-13 12:27
Hello @Omar1892,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain

**Closed** 2021-12-13 12:27 UTC
Labels: Manage Tickets
